//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWEBApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieWEBApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ActorsDirectorsCodes_IMDB {
            get {
                object obj = ResourceManager.GetObject("ActorsDirectorsCodes_IMDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nconst	primaryName	birthYear	deathYear	primaryProfession	knownForTitles
        ///nm0000001	Fred Astaire	1899	1987	soundtrack,actor,miscellaneous	tt0043044,tt0050419,tt0053137,tt0072308
        ///nm0000002	Lauren Bacall	1924	2014	actress,soundtrack	tt0117057,tt0037382,tt0038355,tt0071877
        ///nm0000003	Brigitte Bardot	1934	\N	actress,soundtrack,producer	tt0057345,tt0059956,tt0049189,tt0054452
        ///nm0000004	John Belushi	1949	1982	actor,writer,soundtrack	tt0077975,tt0072562,tt0080455,tt0078723
        ///nm0000005	Ingmar Bergman	1918	2007	writer,di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActorsDirectorsNames_IMDB {
            get {
                return ResourceManager.GetString("ActorsDirectorsNames_IMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movieId,imdbId,tmdbId
        ///1,0114709,862
        ///2,0113497,8844
        ///3,0113228,15602
        ///4,0114885,31357
        ///5,0113041,11862
        ///6,0113277,949
        ///7,0114319,11860
        ///8,0112302,45325
        ///9,0114576,9091
        ///10,0113189,710
        ///11,0112346,9087
        ///12,0112896,12110
        ///13,0112453,21032
        ///14,0113987,10858
        ///15,0112760,1408
        ///16,0112641,524
        ///17,0114388,4584
        ///18,0113101,5
        ///19,0112281,9273
        ///20,0113845,11517
        ///21,0113161,8012
        ///22,0112722,1710
        ///23,0112401,9691
        ///24,0114168,12665
        ///25,0113627,451
        ///26,0114057,16420
        ///27,0114011,9263
        ///28,0114117,17015
        ///29,0112682,902
        ///30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string links_IMDB_MovieLens {
            get {
                return ResourceManager.GetString("links_IMDB_MovieLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MovieCodes_IMDB {
            get {
                object obj = ResourceManager.GetObject("MovieCodes_IMDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ratings_IMDB {
            get {
                object obj = ResourceManager.GetObject("Ratings_IMDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagId,tag
        ///1,007
        ///2,007 (series)
        ///3,18th century
        ///4,1920s
        ///5,1930s
        ///6,1950s
        ///7,1960s
        ///8,1970s
        ///9,1980s
        ///10,19th century
        ///11,3d
        ///12,70mm
        ///13,80s
        ///14,9/11
        ///15,aardman
        ///16,aardman studios
        ///17,abortion
        ///18,absurd
        ///19,action
        ///20,action packed
        ///21,adaptation
        ///22,adapted from:book
        ///23,adapted from:comic
        ///24,adapted from:game
        ///25,addiction
        ///26,adolescence
        ///27,adoption
        ///28,adultery
        ///29,adventure
        ///30,affectionate
        ///31,afi 100
        ///32,afi 100 (laughs)
        ///33,afi 100 (movie quotes)
        ///34,africa
        ///35,afterlife
        ///36,aging
        ///37,aids
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TagCodes_MovieLens {
            get {
                return ResourceManager.GetString("TagCodes_MovieLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movieId,tagId,relevance
        ///1,1,0.029000000000000026
        ///1,2,0.023749999999999993
        ///1,3,0.05425000000000002
        ///1,4,0.06874999999999998
        ///1,5,0.15999999999999998
        ///1,6,0.19524999999999998
        ///1,7,0.07600000000000001
        ///1,8,0.252
        ///1,9,0.22749999999999998
        ///1,10,0.02400000000000002
        ///1,11,0.587
        ///1,12,0.09425
        ///1,13,0.178
        ///1,14,0.007000000000000006
        ///1,15,0.035250000000000004
        ///1,16,0.21450000000000002
        ///1,17,0.013500000000000012
        ///1,18,0.09725
        ///1,19,0.66825
        ///1,20,0.25725
        ///1,21,0.35724999999999996
        ///1,22,0.30225
        ///1,23,0.04975000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TagScores_MovieLens {
            get {
                return ResourceManager.GetString("TagScores_MovieLens", resourceCulture);
            }
        }
    }
}
